### ISSUE TITLE
bug using NavBar widget

### ISSUE THREAD

**Issue by SaqibZafar** [MacGyer/yii2-materializecss#1]
PHP Compile Error – yii\base\ErrorException

macgyer\yii2materializecss\lib\BaseWidget and macgyer\yii2materializecss\lib\MaterializeWidgetTrait define the same property ($clientOptions) in the composition of macgyer\yii2materializecss\widgets\NavBar. However, the definition differs and is considered incompatible. Class was composed

**Comment by SaqibZafar** [comment]
had to remove line 
use MaterializeWidgetTrait;
in NavBar widget to get it working.

**Comment by MacGyer** [comment]
fixed in https://github.com/MacGyer/yii2-materializecss/commit/9aa5528a0b042f2a52439a595c74836f6ba01a7d
