### ISSUE TITLE
Time Picker support

### ISSUE THREAD

**Issue by macagua** [MacGyer/yii2-materializecss#10]
Hi @MacGyer 

It's would be good add support for a Time Picker for yii2-materializecss extension. Actually the materializecss framework, by default supports a DatePicker widget based [pickadate.js](http://amsul.ca/pickadate.js/) library, but this library also have support for [Time Picker](http://amsul.ca/pickadate.js/time/).

To resolve this requirement, I have been created a new Time Picker based on DatePicker widget from yii2-materializecss extension. For this widget to work, I had to add a new line "require" configurations via the "composer" tool, this is because "materializecss" does not distribute the original file named "picker.time.js" used for "time picker".

A example of TimePicker widget is like:

```php
<?=
  echo $formRoute->field($cRoute, 'pickup_time')->widget(
    TimePicker::classname(), [
      // More client options http://amsul.ca/pickadate.js/time/#options
      'clientOptions' => [
        // Close on a user action
        'closeOnSelect' => true,
        // Display a Time format in human-friendly label.
        'format' => 'h:i A',
        // Time format use to submit.
        'formatSubmit' => 'HH:ii:ss',
        // The interval between each time
        'interval' => 30
        // Set the minimum and maximum selectable times on the picker
        // 'min' => [7,30],
        // 'max' => [20,0],
      ],
      'options' => [
        'placeholder' => 'Enter event time...',
        'readonly'=>'readonly',
        'class'=>'col m6',
      ],
    ]
  )->label('Pickup Time');
?>
```

That render the following widget:

![timepicker - materilizecss](https://cloud.githubusercontent.com/assets/185395/15628602/bbc5b566-24ce-11e6-9ec1-3ff7e786ee16.png)

@MacGyer Then my intention with this report is to contribute to this excellent extension adding this new Widget, you would like to include?

**Comment by MacGyer** [comment]
Hey @macagua,


thanks for getting back, and with great work. I will check your code and idea.
Currently I am still working on the documentation page for this repo, so it might take some time before I can make the next steps with this.

Again, thanks for sharing your thoughts.

Cheers

**Comment by MacGyer** [comment]
Could you please provide me with a pull request containing all necessary files? Thanks

**Comment by macagua** [comment]
@MacGyer make this improvements into **develop** or **master** branch?

**Comment by MacGyer** [comment]
always develop please

**Comment by MacGyer** [comment]
@macagua: I opened up a feature branch. please create the PR for this branch: https://github.com/MacGyer/yii2-materializecss/tree/feature/time-picker

**Comment by macagua** [comment]
@MacGyer I'm on my way
