### ISSUE TITLE
How define a "onSet" function from DatePicker widget

### ISSUE THREAD

**Issue by macagua** [MacGyer/yii2-materializecss#14]
Hi @MacGyer 

I am trying to define a "onSet" function from DatePicker widget because the DatePicker from materializecss have the "closeOnSelect" parameters option doesn't work (the issue was reported https://github.com/Dogfalo/materialize/issues/870) and the solution is defining a "onSet" function like the following:

```
    onSet: function () {
        this.close();
    }
```

I don't know how set this function with DatePicker widget: 
```
                // Prevent closing on selecting month/year
                'onSet' => 'function () { this.close(); }'
```
Also I tried with this definition:
```
                // Prevent closing on selecting month/year
                'onSet' => function () {
                    this.close();
                }
```

And not yet managed to make the widget is closed by sectioning the date!

Any idea @MacGyer ?

**Comment by MacGyer** [comment]
Hi @macagua 

After your timepicker PR I am reviewing the DatePicker widget source code.
Unfortunately, setting JS handlers currently is not possible.

To solve your problem a workaround is to define a custom DatePicker which ```extends``` my DatePicker and define the ```$clientOptions``` and ```$clientEvents``` properties. After having set your JS functionality, override the ```DatePicker::run()``` method (copy and paste) and call ```$this->registerClientEvents();``` within ```DatePicker::run()```.

The integration of this feature is planned for one of the next releases of DatePicker and TimePicker.

Cheers

**Comment by MacGyer** [comment]
Hi @macagua,

I just have looked into your issue.
Contrary to my statement above, the DatePicker can handle JS functionality through the MaterializeWidgetTrait.

Just define your onSet callback in the $clientOptions field, when setting up the widget:

```
<?= $form->field($someModel, 'some_field')->widget(\macgyer\yii2materializecss\widgets\form\DatePicker::className(), [
    'clientOptions' => [
        'onSet' => new \yii\web\JsExpression("function () {this.close();}"),
   ],
]) ?>
```

**Comment by macagua** [comment]
@MacGyer really thanks is working :+1:
