### ISSUE TITLE
sidenav dropdowns don't work

### ISSUE THREAD

**Issue by atiberius** [MacGyer/yii2-materializecss#16]
When you have submenus (translated in dropdowns) in a NavBar, the dropdowns only work on desktop. When going on mobile (or lower resolution) and sidenav activates, the dropdowns don't work anymore inside it.
I suspect it has to do with the way sidenav elements are copied using .clone(). I don't think this also clones the click handlers as well.

**Comment by MacGyer** [comment]
@atiberius 
Thanks for reporting.
I will investigate the issue and get back.

**Comment by manosl24** [comment]
Dear MacGyer,

Good evening, Nav how to change submenu class dynamically...can you please help me...i try to add lot of way but showing error or now adding class...

**Comment by MacGyer** [comment]
@manosl24 

Could you please open a new issue?
And please be more specific about what you want to do and what you have already tried.

Code examples are appreciated.
