### ISSUE TITLE
To-do ActiveFields

### ISSUE THREAD

**Issue by friek108** [MacGyer/yii2-materializecss#19]
Been trying to work to get the ActiveFields checkboxes, radios, radio lists, checkbox lists feature implemented.. have you got any plans / guidance on how you wanted to progress this? It's proving difficult given the label wrapper not playing nicely https://github.com/Dogfalo/materialize/issues/1376#issuecomment-258676113

**Comment by MacGyer** [comment]
Hey @friek108,

the label display can be easily adapted with CSS.
If you want to change, how label and input are rendered (order) you need to [change the $template property of ActiveField](http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#$template-detail) class.

Anyway, I am bit short of time right now. I am planning to invest more time around Christmas this year to prepare the next release with bug fixes and enhancements.

Cheers

**Comment by MacGyer** [comment]
Hey @friek108,

as mentioned in this issue #20, I am currently working on ActiveField enhancements.

Cheers

**Comment by friek108** [comment]
Cool changes. I think you might have seen this but just in case you might want to take a look at the `function radioList()` and `function dropDownList()`  [here](https://github.com/friek108/yii2-materializecss/blob/master/src/widgets/form/ActiveField.php) in ActiveField.php for a couple of ideas..

**Comment by MacGyer** [comment]
thank you. 
Those lists are in my focus. Going to work on them next time.

**Comment by MacGyer** [comment]
@friek108 dropDownList including Select widget in 0244bf2e556f2ca23289280d4cfb38e62015206f
