### ISSUE TITLE
ActiveForm why not auto register MaterializePluginAsset and MaterializeAsset ?

### ISSUE THREAD

**Issue by vuongminh** [MacGyer/yii2-materializecss#25]
Why we don't register both assets css and js in method run of ActiveForm like base ActiveForm of yii?

**Comment by MacGyer** [comment]
@vuongminh 

I think you are referring to:
https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveForm.php#L212

Why should I register the general [MaterializeAsset](https://github.com/MacGyer/yii2-materializecss/blob/master/src/assets/MaterializeAsset.php) in the ActiveForm?

Did you recognize that the base class does not register any general asset? It only registers the [ActiveFormAsset](https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveFormAsset.php) which is needed for Yii's JS form validation.

I am open for any input why to register the MaterializeAsset in ActiveForm. Go on, looking forward to a constructive discussion.

Cheers

**Comment by vuongminh** [comment]
Great! I agree with your opinion. Thanks.
