### ISSUE TITLE
materialize porject structer

### ISSUE THREAD

**Issue by radhouen** [MacGyer/yii2-materializecss#26]
Hi MacGyer,
thanks for your great work
I have some question:
can you give me a project stucter where you use materialzecss because if I excute the composer code line this require not added to my composer.json also where we can added the file added in zip to my project .
thanks

**Comment by MacGyer** [comment]
Hi @radhouen,

thanks for using this extension.
I'm sorry, but I don't really understand your problem.

Please specifiy exactly what you are trying to do and what does not work.

Did you add
`
"macgyer/yii2-materializecss": "*"
`
to the `required` section of your composer.json?
Did you run `composer update` after adding this line?

Just to make sure: are you actually using Yii2?
Which zip file are you referring to?
Can you show the folder structure of your project?
Do you have a Git repo?

Need more information to help you. 

Cheers

**Comment by radhouen** [comment]
![capture du 2017-03-14 10-22-53](https://cloud.githubusercontent.com/assets/9937606/23893847/5455548e-08a0-11e7-8e02-c3bf0aa499ec.png)
===> this my project and i use yii2 .
so sir can you give me a method steps by steps to add your extension to my project thanks a lot for your quick response

**Comment by MacGyer** [comment]
As stated:

add `"macgyer/yii2-materializecss": "*"` to the `require` block of this composer.json and run composer update.

**Comment by radhouen** [comment]
![capture du 2017-03-14 10-34-31](https://cloud.githubusercontent.com/assets/9937606/23894300/d80f463a-08a1-11e7-92e0-39223ad051d1.png)
I added but always I have this error

**Comment by MacGyer** [comment]
this has nothing to do with the extension. You are using wrong version constraint syntax.
Post your full composer.json

**Comment by radhouen** [comment]
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "dmstr/yii2-adminlte-asset": "2.*",
        "scotthuangzl/yii2-google-chart": "dev-master",
        "philippfrenzel/yii2fullcalendar": "*",
        "kartik-v/yii2-widget-fileinput": "@dev",
        "marekpetras/yii2-calendarview-widget": "^1.0",
        "2amigos/yii2-date-picker-widget": "~1.0",
        "yiisoft/yii2-redis": "^2.0",
        "imanilchaudhari/yii2-social-share": "dev-master",
        "kartik-v/yii2-export": "@dev",
        "kartik-v/yii2-editable": "*",
        "2amigos/yii2-ckeditor-widget": "^2.0",
        "kartik-v/yii2-widget-select2": "@dev",
        "macgyer/yii2-materializecss": "*"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        
        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
    "scripts": {
        "post-install-cmd": "php init --env=Development --overwrite=n"
    }
}

**Comment by MacGyer** [comment]
you didn't do what is needed. You are missing the asterisk in the `"macgyer/yii2-materializecss": ""`.

`"macgyer/yii2-materializecss": "*"`

**Comment by radhouen** [comment]
I'll push my project to git for more details, I'll send you a link  sir thanks

**Comment by radhouen** [comment]
Sir this is my link [](https://github.com/radhouen/Yii2Materializecss) to my project

**Comment by MacGyer** [comment]
no link in your comment

**Comment by radhouen** [comment]
Sir this is my link to my project[Git](https://github.com/radhouen/Yii2Materializecss)

**Comment by MacGyer** [comment]
now the compser line looks fine. run `composer update` and do the rest of the [README](https://github.com/MacGyer/yii2-materializecss/blob/master/README.md). You are set up then.
