### ISSUE TITLE
How to change modal attributes?

### ISSUE THREAD

**Issue by jantivola** [MacGyer/yii2-materializecss#28]
Hi, I'm currently using your modal feature on yii2, i'm just wondering how to:

1.) make Modal be dismissed by clicking outside of the modal
2.) change the opacity of the modal's outside background so users wont be able to click the contents

I'll appreciate your answers, more power!

**Comment by MacGyer** [comment]
Hi @jantivola,

thanks for using yii2-materializecss.
The options you are asking for are handled by the underlying Materialize JS plugin.

You need to provide the options in the `$clientOptions` property of the `Modal` class.
Check [the official docs](http://materializecss.com/modals.html#options) for `dismissible` and `opacity`.

Cheers

**Comment by jantivola** [comment]
Hi MacGyer,

I appreciate your response but I just knew yii2 (had to learn the basics because I'm currently designing an app) and I'm not sure how to provide the options in the `$clientOptions` property of the `Modal` class.

**Comment by MacGyer** [comment]
Hi @jantivola,

you're welcome.
This case is nothing special in Yii2 but in OOP.

As you can see, the `Modal` class extends `BaseWidget`. This class makes use of `MaterializeWidgetTrait`. In this trait the `$clientOptions` (https://github.com/MacGyer/yii2-materializecss/blob/master/src/lib/MaterializeWidgetTrait.php#L41) are declared and thus are available in `Modal`.

Simply set your options in your `Modal` like follows:

```
<?php Modal::begin([
    'clientOptions' => [
        'dismissible' => true,
        'opacity' => 0.8,
    ],
    // other Modal config options
]) ?>

// Your modal content

<?php Modal::end() ?>
```

For more information on the class structure, please check the [API docs](http://macgyer.github.io/yii2-materializecss/api/).

Have fun.

**Comment by jantivola** [comment]
Thank you! I will surely apply this and also read the link you gave. More power!
