### ISSUE TITLE
Checkbox not clickable

### ISSUE THREAD

**Issue by robov** [MacGyer/yii2-materializecss#30]
I managed to display the checkbox, but not it is not clickable ?
```
                echo $form->field($model, 'rememberMe')->checkbox([],false);
```

**Comment by robov** [comment]
```
use macgyer\yii2materializecss\widgets\form\ActiveForm;
```
and I even tried adding
```
use macgyer\yii2materializecss\widgets\form\ActiveField;
```

**Comment by robov** [comment]
After stripping out most of the stuff  I am left with
```

<link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="/assets/cc935e6b/css/materialize.min.css" rel="stylesheet"></head>
```
and
```
<script src="/assets/ffb9a78f/jquery.js"></script>
 <script src="/assets/5982fb8b/yii.js"></script>
 <script src="/assets/5982fb8b/yii.validation.js"></script>
 <script src="/assets/5982fb8b/yii.activeForm.js"></script>
 <script src="/assets/cc935e6b/js/materialize.min.js"></script>
```
But the checkbox is still not clickable

**Comment by MacGyer** [comment]
Hi @robov,

thanks for using yii2-materializecss.

I am going to investigate your issue. Can you post a link or fiddle or screenshot to have a look?

Cheers

**Comment by robov** [comment]
I just took all the testcode out, so I cannot at the moment.. maybe later...

**Comment by robov** [comment]
Thanks for looking into this

**Comment by MacGyer** [comment]
Wow ... have a fiddle here: https://jsfiddle.net/bpgbL27j/1/

The culprit is the `<div class="input-field">`. If this CSS class is omitted, it works like expected.
I need to investigate further to find out whether this is expected behaviour or a bug.

Will get in touch with [Materialize](https://github.com/dogfalo/materialize) for more information.

To make it work you can use the following workaround:

```php
<?= $form->field($yourModel, 'your_property', ['options' => ['class' => false]])->checkbox() ?>
```


Cheers

**Comment by MacGyer** [comment]
This issue definitely lies on Materialize's side:

https://github.com/Dogfalo/materialize/issues/5062

You need to apply the workaround mentioned above.
I will wait for an official statement from Materialize. Either they fix it or will update their docs telling us to not put checkboxes into `<div class="input-field"></div>`
