### ISSUE TITLE
jquery.js:253 Uncaught Error: Method hide does not exist on jQuery.modal

### ISSUE THREAD

**Issue by robov** [MacGyer/yii2-materializecss#31]
When I add 
```
\macgyer\yii2materializecss\assets\MaterializeAsset::register($this);        
\macgyer\yii2materializecss\assets\MaterializePluginAsset::register($this);  
```

then my old line breaks
```
jQuery('#WaitDialog_Modal').modal('hide')
```

![image](https://user-images.githubusercontent.com/8173436/29563496-2542ea0e-873e-11e7-9969-4a5532c10d7d.png)

**Comment by MacGyer** [comment]
Do you have, by any chance, manually included a jQuery version that conflicts with the jQuery version loaded by ´MaterializePluginAsset`?

I assume this because you are speaking of "old line".

Try to remove your jQuery version or use your jQuery with `noConflict()`
BTW: any source?

**Comment by MacGyer** [comment]
Anything new here? If not I am closing this issue.
