### ISSUE TITLE
clientOptions or options?

### ISSUE THREAD

**Issue by wardjk** [MacGyer/yii2-materializecss#34]
In Nav.php, line 272, should 'clientOptions' instead be 'options'? In SideNav.php, the variable clientOptions is declared but not referenced but $this->options is.

**Comment by MacGyer** [comment]
No... it's correct.

You can declare the `$clientOptions` for SideNav in Nav which are then passed to SideNav. `$clientOptions` are the options for the underlying JS plugin (`sideNav()` in this case).
Those `$clientOptions` are used by [MaterializeWidgetTrait](https://github.com/MacGyer/yii2-materializecss/blob/master/src/lib/MaterializeWidgetTrait.php#L73).

`$options` are the actual options for the widget itself or the widget container.

Every widget is extending `BaseWidget` or `BaseInputWidget`, thus `$options` is always available.

Step through with xdebug to see how those options are passed and referenced.
