### ISSUE TITLE
GridView Select filter lost with Pjax

### ISSUE THREAD

**Issue by wardjk** [MacGyer/yii2-materializecss#35]
GridView filters for an array are built as a select element. Materialize sets "display: none" for the select. This can be countered by setting the class to 'browser-default'. A macgyer\yii2materializecss\widgets\form\Select (essentially a material_select() as a ul) can be used instead. The Select filter shows fine initially but if Pjax is used, it ends up as a select instead of a ul. Is there a way a Select be used as a filter when also using Pjax?

**Comment by MacGyer** [comment]
Can you please provide a link?

**Comment by wardjk** [comment]
No. I'm just trying yii2-materializecss on a dev machine. For a live site I wouldn't use both Pjax & Select until I can figure out how to make everything work properly together. Have you used GridView w/ Pjax + Select filter?

**Comment by wardjk** [comment]
After a pjax update, a <select> must be initialized again. Say we have a grid with two columns with filters using <select> having ids of "attribute1" and "attribute2". After sorting or filtering, this would reinitialize the selects:
`$(document).on('pjax:success', function() {
	$('#attribute1').material_select();
	$('#attribute2').material_select();
});`
I extended GridView to achieve similar functionality.

**Comment by MacGyer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PJAX-Select](https://trello.com/c/41mi6BKd/38-pjax-select)

**Comment by wardjk** [comment]
Trello reports: "Card not found. This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams."
