### ISSUE TITLE
Renserize view in modal and change button by default?

### ISSUE THREAD

**Issue by Pedro25** [MacGyer/yii2-materializecss#40]
I have two questions:

1. The first is how I render a view (an action) within the modal, because in bootstrap I did it in the following way:

![screenshot_2](https://user-images.githubusercontent.com/11860409/32153873-801f1a10-bd03-11e7-8584-4a31fb65fab3.png)

But I can not find the form of acerlo with macgyer \ yii2materializecss \ widgets \ Modal.

2. The second question is how to achieve that modal trigger from a fixed-action-btn button. For example:

![screenshot_3](https://user-images.githubusercontent.com/11860409/32153942-c2df02de-bd03-11e7-9c3b-af50cf050f46.png)

I would really appreciate any help you can give me. Thank you very much.

**Comment by MacGyer** [comment]
Hi @Pedro25,

the Modal widget works the same way as the Bootstrap version.
All code between `Modal::begin()` and `Modal::end()` will be treated as Modal content.

Regarding your button:
Please check the config options for the toggle button. To render the FAB you can use the respective widget.

**OR:**

Simply create your own Modal widget which extends the Modal class. Then you can implement your own toggle button rendering logic.

**Comment by Pedro25** [comment]
Hola MacGyer,

I appreciate your response, I'm not sure how to link the content that will be in the modal to an external view.

Can you help me?

**Comment by MacGyer** [comment]
Hi,

I am not sure whether I am understanding you correctly.

What about this?
```
<?= Modal::begin() ?>
<?= $this->render('/path/to/view'); ?>
<?= Modal::end() ?>
```

**Comment by Pedro25** [comment]
If I use 

`$this->render('/example/create')` 

inside the modal that is in index then I have to use          

`$this->render('_ form', ['model'=>$model])`

 in the view of create, I do not know if you understand.

It is a not practical solution.

That's why I use the form of acertra in bootstrap:

![screenshot_1](https://user-images.githubusercontent.com/11860409/32349508-b69c4cce-bfed-11e7-8656-4b3cc81867c0.png)

**Comment by MacGyer** [comment]
Sorry, I do not understand...

What is so impractical of passing the variable into both views? It's standard Yii practice. 

What exactly are you trying to do?
What shall be the result?

Do you have a working example with the Bootstrap version?

**Comment by Pedro25** [comment]
Sorry for not explaining.

In this link is exactly what I want to try to do with the materializecss modal:

http://www.yiiframework.com/wiki/806/render-form-in-popup-via-ajax-create-and-update-with-ajax-validation-also-load-any-page-via-ajax-yii-2-0-2-3/

**Comment by MacGyer** [comment]
Why don't you just do what is stated in the example?
This has nothing to do with the Modal (Bootstrap or Materialize).

Or are you explicitely meaning the following passage:

> Add the bootstrap modal to your layouts main.php file. I put it at the very end after all of my scripts.

It does not matter, where the modal is being placed, imho.
