### ISSUE TITLE
How to use autocomplete?

### ISSUE THREAD

**Issue by developer2wsx** [MacGyer/yii2-materializecss#41]
Hi @MacGyer. Thank you for your contribution to those who use yii2.

I would like to know if there is any example of how to use materialize autocomplete with yii2-materializecss.

**Comment by MacGyer** [comment]
Hi @developer2wsx,


thanks for using this Yii2 extension.

To use autocomplete you simply need to put an `autocomplete` array into the field options.
Check PHPdoc:

https://github.com/MacGyer/yii2-materializecss/blob/master/src/widgets/form/ActiveField.php#L157
https://github.com/MacGyer/yii2-materializecss/blob/master/src/widgets/form/ActiveField.php#L513
