### ISSUE TITLE
Does not highlight "invalid" form field

### ISSUE THREAD

**Issue by alexander-lysenko** [MacGyer/yii2-materializecss#43]
I've tried your "Materialize for Yii2" (version 2.0.2).
While using widget ` ActiveForm`, my form fields are not highlited as invalid after validation.
![2018-05-24 16-05-45](https://user-images.githubusercontent.com/16338936/40488487-8f661af0-5f6f-11e8-8473-7164aaec8fc4.jpg)
I detected that tag `<input ... class="validate">` does not get class 'invalid' after validation. If I add this manually, the field's highlight works.
![2018-05-24 16-15-51](https://user-images.githubusercontent.com/16338936/40489206-44c115c0-5f71-11e8-81cb-bc15dd50f4b6.jpg)
Also I have a problem with `<div class="help-block">...</div>`, which contains error message for this field. In [Materialize official documentation](https://materializecss.com/text-inputs.html#input) it shows as `<span class="helper-text" data-error="wrong" data-success="right">Helper text</span>` and is highlighted correctly.
![2018-05-24 16-42-20](https://user-images.githubusercontent.com/16338936/40489309-7c23e1e6-5f71-11e8-9c3c-e90d87a00793.png)

Yii2 version: 2.0.14
PHP version: 7.2

**Comment by MacGyer** [comment]
Hi @Alexander-Lysenko,

thanks for using this extension and reporting the issue.
I will take a look into it.

Currently I am working on version 3, which will be using Materialize 1.0.
To fix your issue without waiting for a 2.x bugfix, you could try to mimic the materialize css styles for the current markup.

Hope to have a bugfix ready shortly.

Cheers
