### ISSUE TITLE
Provided main layout not working.

### ISSUE THREAD

**Issue by alvarolordelo** [MacGyer/yii2-materializecss#45]
after copy in the src main layout file, it loads wrong asset
**
frontend\assets\AppAsset::register($this); on line 12. from src/layout/main.php

Please fix that call to make the page work.

yii2 2.18 - the newest install - and using yii2 - materialise 3

**Comment by MacGyer** [comment]
`frontend\assets\AppAsset::register($this);`

That's 100% correct as it loads the AppAsset provided by the Yii2 application.

Did you read: https://github.com/MacGyer/yii2-materializecss#usage?

There you have two ways of how to require the Materialize sources.
