### ISSUE TITLE
provide an useful initial project

### ISSUE THREAD

**Issue by alvarolordelo** [MacGyer/yii2-materializecss#46]
https://materializecss.com/templates/starter-template/preview.html
that's a example of materialize project - so using your project with the layout on src - it isn't working as expected - why do you have so much effort to make all the widgets since the main layout won't work.
![image](https://user-images.githubusercontent.com/1663952/57174139-e1995d00-6e0f-11e9-81e5-6363885b0d35.png)

just uploaded here a what could be the yii2-materialize

**Comment by MacGyer** [comment]
It was never intended to provide a styled template with the package.

First: Yii2 brings its own template (basic or advanced app).
Second: This Materialize starter template you linked to has styles which differ from the default Materialize stylesheet.

For a working example I would need to provide a complete Yii2 basic (or advanced) application with content, markup and styles applied. This was never the object of the package.

You integrate the library, widgets, etc. and are solely responsible for the markup, structure (controller, view, etc.) and styling of your site.

But nonetheless, maybe I am going to provide an example app in a separate repo. Time is short right now.
