### ISSUE TITLE
ActiveForm isn't working - must set active on label after click

### ISSUE THREAD

**Issue by alvarolordelo** [MacGyer/yii2-materializecss#48]
![image](https://user-images.githubusercontent.com/1663952/58447308-6196a800-80da-11e9-81e3-fe335e0a3b82.png)

when you click on input it should set active to be able the label move up, now it's just blurring

**Comment by MacGyer** [comment]
![image](https://user-images.githubusercontent.com/2939625/58456361-45b7f400-8124-11e9-8a81-b74c7ba57874.png)

Works like it should.

Please check that you are using `macgyer\yii2materializecss\widgets\form\ActiveForm` in your form view.
