### ISSUE TITLE
Alert isn't working

### ISSUE THREAD

**Issue by alvarolordelo** [MacGyer/yii2-materializecss#49]
macgyer\yii2materializecss\widgets\Alert;  isn't rendering properly

![image](https://user-images.githubusercontent.com/1663952/58448589-d7047780-80de-11e9-85b0-c6ade09f3942.png)

**Comment by alvarolordelo** [comment]
Yii::$app->session->setFlash('success', 'Alert success');
        Yii::$app->session->setFlash('error', 'Alert error');
        Yii::$app->session->setFlash('info', 'Alert info');
        Yii::$app->session->setFlash('danger', 'Alert danger');
        Yii::$app->session->setFlash('warning', 'Alert warning');

**Comment by alvarolordelo** [comment]
Version 3.0 is working on your repo?
It seems I'm using some outdated commit since all the provided src isn't working...

**Comment by MacGyer** [comment]
Yes, it is working as expected.

As Materialize is **not** providing any alert/contextual color scheme or elements, you have to style them as you need.

Did you check the rendered HTML?

```
<div id="w9-success-0" class="alert success">
	<div class="card-panel">Alert success</div>
</div>

<div id="w9-error-0" class="alert error">
<div class="card-panel">Alert error</div>
</div>

<div id="w9-info-0" class="alert info">
	<div class="card-panel">Alert info</div>
</div>

<div id="w9-danger-0" class="alert danger">
	<div class="card-panel">Alert danger</div>
</div>

<div id="w9-warning-0" class="alert warning">
	<div class="card-panel">Alert warning</div>
</div>
```

Simply write your CSS and you're done.
