### ISSUE TITLE
BreadCrumbs rendering with some failure

### ISSUE THREAD

**Issue by alvarolordelo** [MacGyer/yii2-materializecss#50]
I've put it with row attribute on the class to show more properly...

`<?=
         Breadcrumbs::widget([
                    'options' => ['class' => 'row'],
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]);
  ?>`
I've figured that way to show it more precisely.

**Comment by MacGyer** [comment]
And what is the failure now?
