### ISSUE TITLE
PHP 8 compatibility issue

### ISSUE THREAD

**Issue by mpasang** [MacGyer/yii2-materializecss#53]
Unparenthesized `a ? b : c ? d : e` is not supported in PHP 8. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in https://github.com/MacGyer/yii2-materializecss/blob/3fb85450e72ad0458c60e7f46a9a8e42989e90af/src/widgets/form/SwitchButton.php#L155

**Comment by MacGyer** [comment]
fixed in https://github.com/MacGyer/yii2-materializecss/releases/tag/4.0.0-RC1
