### ISSUE TITLE
Yii2 Layout template wanted!

### ISSUE THREAD

**Issue by devleaks** [MacGyer/yii2-materializecss#6]
Hello,

I'd appreciate a set of layout files for a standard Yii app.
Layout would include header, nav bar, and footer at least.

Thank you.

**Comment by MacGyer** [comment]
Hello,

as I have never worked with Yii basic app, can you please tell me whether there are any differences between the main layout in basic and advanced app?

Regards

**Comment by devleaks** [comment]
Hello,
No there aren't any difference. Basic/advanced it's just app structure.
P.

**Comment by MacGyer** [comment]
added https://github.com/MacGyer/yii2-materializecss/commit/793fc726a02878a58c958bd110626de31c16b42d
