### ISSUE TITLE
Don't work Determinate Lineal Spinner (Lineal Preloader)

### ISSUE THREAD

**Issue by macagua** [MacGyer/yii2-materializecss#7]
Hi @MacGyer 

I am trying to do a [Determinate Lineal Spinner](http://materializecss.com/preloader.html#linear) (Lineal Preloader) with the following code:

```php
use macgyer\yii2materializecss\widgets\Progress;

echo Progress::widget([
    // the HTML attributes for the widget container tag.
    'options' => ['class' => 'progress'],
    //  HTML attributes for the progress tag.
    'progressOptions' => [
        'type' => 'determinate',
        'width' => 55,
    ],
]);
```

This renders the HTML code:

```html
<div id="w0" class="progress">
    <div type="determinate" class="indeterminate" width="55"></div>
</div>
```

If I use the "Developer Inspect Tool" from my Web Browser and modified my HTML rendered like the following code:

```html
<div class="progress">
    <div class="determinate" style="width: 70%"></div>
</div>
```
That way the determinate lineal spinner it works well!

Checking the source code at **@vendor/macgyer/yii2-materializecss/src/widgets/Progress.php**

```php
        if ($this->type === 'determinate') {
            Html::addCssStyle($this->progressOptions, ['width' => $this->value . '%']);
        }
```

Maybe this need some source code like this:

```php
        if ($this->type === 'determinate') {
            Html::addCssClass($this->progressOptions, ['class' => 'determinate']);
            Html::addCssStyle($this->progressOptions, ['width' => $this->value . '%']);
        }
```

I hope your comments :+1:

**Comment by MacGyer** [comment]
Hi @macagua 

thx for putting this up. I will look into the issue and provide a fix if needed.

**Comment by MacGyer** [comment]
Hi @macagua 


the widget works as expected, but unfortunately you have misunderstood the configuration. To achieve what you wanted, you need to use the following code:

```
<?= \macgyer\yii2materializecss\widgets\Progress::widget([
    'type' => 'determinate',
    'value' => 55,
]) ?>
```

You do not need to specifiy any options for a simple determinate progress bar. Be sure to set the type and value properties correctly. You have included those in the ```progressOptions``` which are rendered as HTML attributes for the inner ```div```.

The ```<div class="progress">``` is automatically generated if you omit the ```options```.

By the way: thx for using!

Cheers

**Comment by macagua** [comment]
@MacGyer thanks for your answer, is so useful!
