### ISSUE TITLE
Add reference to use macgyer/yii2-materializecss

### ISSUE THREAD

**Issue by macagua** [MacGyer/yii2-materializecss#8]
Hi @MacGyer 

Add reference to use _macgyer/yii2-materializecss_

That would be great a source code reference like snippet source code to use macgyer/yii2-materializecss.

**Comment by macagua** [comment]
@MacGyer a example here

https://github.com/EZTechVe/yii2-materializecss/blob/develop/USAGE.md

**Comment by MacGyer** [comment]
Hi @macagua 

I am currently planning to setup a comprehensive demo page. Thanks for your work at https://github.com/EZTechVe/yii2-materializecss/blob/develop/USAGE.md

**Comment by macagua** [comment]
@MacGyer there are no problem to merge this recipe file via a pull request?

**Comment by MacGyer** [comment]
Hi @macagua 

the first part of the knowledge base has been published right now:
http://macgyer.github.io/yii2-materializecss/api/

Have fun reading and working...

Cheers

**Comment by MacGyer** [comment]
Hi @macagua,

it is done. Alright, not 100%, but the demo/documentation page is online right now:
[yii2-materializecss demo page](http://yii2-materializecss.pluspunkt-coding.de/).

This page is far from completed. Further chapters are going to be released.
Have a look and get inspired.

Cheers

**Comment by MacGyer** [comment]
closed https://github.com/MacGyer/yii2-materializecss/commit/d9c7bf1e6f60e68c49cef737e7cddaf6158954d2
